@startuml
skinparam DefaultFontName OppoSans M
skinparam linetype polyline
skinparam linetype ortho
left to right direction

title 班车管理

actor 管理员
actor 后勤管理

管理员 -->添加班次
管理员 --->删除班次
管理员 -->查找班次
管理员 -->编辑班次
管理员 -->预约班次
管理员 ->取消预约

后勤管理 -->预约班次
后勤管理 -->取消预约

添加班次 --> 填写截止时间
修改班次 -> 填写截止时间
rectangle 添加班次{
    usecase 填写班车信息 as add1

    usecase 保存
    添加班次 .> add1
    add1 .> 填写截止时间 : 选择填写时间
    add1 .> 保存 : 不选择填写时间

}

rectangle 填写截止时间{
    usecase 保存成功
    usecase 保存失败
    填写截止时间 ...> 保存成功:截止时间晚于当前时间
    填写截止时间 ...> 保存失败:截止时间不晚于当前时间
}
rectangle 删除班次{
}
rectangle 查找班次{
    usecase 选择查找方式
    usecase 输入关键词
    usecase 查找
    查找班次 .> 选择查找方式
    选择查找方式 .> 输入关键词
    输入关键词 .> 查找
}
rectangle 编辑班次{
    usecase 修改班车信息
    usecase 保存

    编辑班次 ..> 修改班车信息
    修改班车信息 ..>保存
}

rectangle 预约班次{
    usecase 选择要预约的班次 as reserve1
    usecase 选择入住人
    usecase 预约成功
    usecase 预约失败

    预约班次 .> reserve1
    reserve1 .> 选择入住人
    选择入住人 .> 预约成功 : 预约时间早于截止时间
    选择入住人 .> 预约失败 : 预约时间不早于截止时间
}
rectangle 取消预约{
}
@enduml