@startuml
'https://plantuml.com/use-case-diagram

skinparam defaultFontName "OppoSans M"
skinparam linetype polyline
skinparam linetype ortho
left to right direction
actor 用户

用户-->(启动程序)

启动程序-->(登录)

rectangle 用户输入{
    usecase “输入姓名”
    登录 ..> 输入姓名 : include
    usecase “输入密码”
    登录 .> 输入密码 : include
}

用户输入 --> (判断输入)

rectangle 判断输入{
    usecase “输入正确”
    usecase “输入错误”
    usecase “未输入信息”
}

usecase 进入主界面
输入正确 --> 进入主界面
输入错误 ---> 用户输入 : 提示用户重新输入
未输入信息 ---> 用户输入 : 提示用户输入信息
@enduml